//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HldsLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HldsLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active server.
        /// </summary>
        public static string aes_ActiveServer {
            get {
                return ResourceManager.GetString("aes_ActiveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new server.
        /// </summary>
        public static string aes_AddNewServerTitle {
            get {
                return ResourceManager.GetString("aes_AddNewServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aditional arguments:.
        /// </summary>
        public static string aes_AditionalArgs {
            get {
                return ResourceManager.GetString("aes_AditionalArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All processors.
        /// </summary>
        public static string aes_AllProcessors {
            get {
                return ResourceManager.GetString("aes_AllProcessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto server restart on crash.
        /// </summary>
        public static string aes_AutoRestart {
            get {
                return ResourceManager.GetString("aes_AutoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string aes_Browse {
            get {
                return ResourceManager.GetString("aes_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string aes_Cancel {
            get {
                return ResourceManager.GetString("aes_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrated.
        /// </summary>
        public static string aes_ConsoleTypeIntegrated {
            get {
                return ResourceManager.GetString("aes_ConsoleTypeIntegrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native.
        /// </summary>
        public static string aes_ConsoleTypeNative {
            get {
                return ResourceManager.GetString("aes_ConsoleTypeNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not restart server, if it crashed.
        /// </summary>
        public static string aes_CrashLimit {
            get {
                return ResourceManager.GetString("aes_CrashLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time(s) in.
        /// </summary>
        public static string aes_CrashLimit2 {
            get {
                return ResourceManager.GetString("aes_CrashLimit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds..
        /// </summary>
        public static string aes_CrashLimit3 {
            get {
                return ResourceManager.GetString("aes_CrashLimit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing server &quot;{0}&quot;.
        /// </summary>
        public static string aes_EditServerTitle {
            get {
                return ResourceManager.GetString("aes_EditServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game:.
        /// </summary>
        public static string aes_Game {
            get {
                return ResourceManager.GetString("aes_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoldSource server.
        /// </summary>
        public static string aes_GoldSourceServer {
            get {
                return ResourceManager.GetString("aes_GoldSourceServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Htlv server.
        /// </summary>
        public static string aes_HltvServer {
            get {
                return ResourceManager.GetString("aes_HltvServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name:.
        /// </summary>
        public static string aes_HostName {
            get {
                return ResourceManager.GetString("aes_HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string aes_Loading {
            get {
                return ResourceManager.GetString("aes_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map:.
        /// </summary>
        public static string aes_Map {
            get {
                return ResourceManager.GetString("aes_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max players:.
        /// </summary>
        public static string aes_MaxPlayers {
            get {
                return ResourceManager.GetString("aes_MaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noipx.
        /// </summary>
        public static string aes_NoIpx {
            get {
                return ResourceManager.GetString("aes_NoIpx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nomaster.
        /// </summary>
        public static string aes_NoMaster {
            get {
                return ResourceManager.GetString("aes_NoMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to hlds.exe:.
        /// </summary>
        public static string aes_PathToHlds {
            get {
                return ResourceManager.GetString("aes_PathToHlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to hltv.exe:.
        /// </summary>
        public static string aes_PathToHltv {
            get {
                return ResourceManager.GetString("aes_PathToHltv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to srcds.exe:.
        /// </summary>
        public static string aes_PathToSrcds {
            get {
                return ResourceManager.GetString("aes_PathToSrcds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor {0}.
        /// </summary>
        public static string aes_Processor {
            get {
                return ResourceManager.GetString("aes_Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processors (cores):.
        /// </summary>
        public static string aes_ProcessorsCores {
            get {
                return ResourceManager.GetString("aes_ProcessorsCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rcon password:.
        /// </summary>
        public static string aes_Rcon {
            get {
                return ResourceManager.GetString("aes_Rcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string aes_Save {
            get {
                return ResourceManager.GetString("aes_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console position:.
        /// </summary>
        public static string aes_ServerConsolePosition {
            get {
                return ResourceManager.GetString("aes_ServerConsolePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console type:.
        /// </summary>
        public static string aes_ServerConsoleType {
            get {
                return ResourceManager.GetString("aes_ServerConsoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP:.
        /// </summary>
        public static string aes_ServerIP {
            get {
                return ResourceManager.GetString("aes_ServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server port:.
        /// </summary>
        public static string aes_ServerPort {
            get {
                return ResourceManager.GetString("aes_ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server priority:.
        /// </summary>
        public static string aes_ServerPriority {
            get {
                return ResourceManager.GetString("aes_ServerPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Above normal.
        /// </summary>
        public static string aes_ServerPriorityAboveNormal {
            get {
                return ResourceManager.GetString("aes_ServerPriorityAboveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below normal.
        /// </summary>
        public static string aes_ServerPriorityBelowNormal {
            get {
                return ResourceManager.GetString("aes_ServerPriorityBelowNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string aes_ServerPriorityHigh {
            get {
                return ResourceManager.GetString("aes_ServerPriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string aes_ServerPriorityIdle {
            get {
                return ResourceManager.GetString("aes_ServerPriorityIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string aes_ServerPriorityNormal {
            get {
                return ResourceManager.GetString("aes_ServerPriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real time.
        /// </summary>
        public static string aes_ServerPriorityRealTime {
            get {
                return ResourceManager.GetString("aes_ServerPriorityRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Properties.
        /// </summary>
        public static string aes_ServerProperties {
            get {
                return ResourceManager.GetString("aes_ServerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source server.
        /// </summary>
        public static string aes_SourceServer {
            get {
                return ResourceManager.GetString("aes_SourceServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sv__lan.
        /// </summary>
        public static string aes_SvLan {
            get {
                return ResourceManager.GetString("aes_SvLan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sys__ticrate:.
        /// </summary>
        public static string aes_SysTicrate {
            get {
                return ResourceManager.GetString("aes_SysTicrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAC (Valve Anti Cheat).
        /// </summary>
        public static string aes_Vac {
            get {
                return ResourceManager.GetString("aes_Vac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error. Send report to developer?.
        /// </summary>
        public static string app_CriticalError {
            get {
                return ResourceManager.GetString("app_CriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is already running.
        /// </summary>
        public static string app_mb_AlreadyStarted {
            get {
                return ResourceManager.GetString("app_mb_AlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start.
        /// </summary>
        public static string app_mb_AlreadyStartedTitle {
            get {
                return ResourceManager.GetString("app_mb_AlreadyStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit program.
        /// </summary>
        public static string br_Close {
            get {
                return ResourceManager.GetString("br_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue working (not recommended).
        /// </summary>
        public static string br_Continue {
            get {
                return ResourceManager.GetString("br_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug report sending failed..
        /// </summary>
        public static string br_mb_Fail {
            get {
                return ResourceManager.GetString("br_mb_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send failed.
        /// </summary>
        public static string br_mb_FailTitle {
            get {
                return ResourceManager.GetString("br_mb_FailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug report successful sended..
        /// </summary>
        public static string br_mb_Successful {
            get {
                return ResourceManager.GetString("br_mb_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send successful.
        /// </summary>
        public static string br_mb_SuccessfulTitle {
            get {
                return ResourceManager.GetString("br_mb_SuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart program.
        /// </summary>
        public static string br_Restart {
            get {
                return ResourceManager.GetString("br_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending report....
        /// </summary>
        public static string br_SendingReport {
            get {
                return ResourceManager.GetString("br_SendingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send report.
        /// </summary>
        public static string br_SendReport {
            get {
                return ResourceManager.GetString("br_SendReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately the program has encountered a problem..
        /// </summary>
        public static string br_WindowMessage {
            get {
                return ResourceManager.GetString("br_WindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error detected.
        /// </summary>
        public static string br_WindowTitle {
            get {
                return ResourceManager.GetString("br_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        public static string do_AutoStartMinimized {
            get {
                return ResourceManager.GetString("do_AutoStartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autostart options.
        /// </summary>
        public static string do_AutoStartOptions {
            get {
                return ResourceManager.GetString("do_AutoStartOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start active servers when program starts after.
        /// </summary>
        public static string do_AutoStartServers {
            get {
                return ResourceManager.GetString("do_AutoStartServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start program when Windows starts.
        /// </summary>
        public static string do_AutoStartWithWindows {
            get {
                return ResourceManager.GetString("do_AutoStartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string do_Cancel {
            get {
                return ResourceManager.GetString("do_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to restart program for the changes to take effect..
        /// </summary>
        public static string do_ChangeLanguageNeedRestart {
            get {
                return ResourceManager.GetString("do_ChangeLanguageNeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Error reporting.
        /// </summary>
        public static string do_ErrorReporting {
            get {
                return ResourceManager.GetString("do_ErrorReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string do_ErrorReportingDisable {
            get {
                return ResourceManager.GetString("do_ErrorReportingDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string do_ErrorReportingEnable {
            get {
                return ResourceManager.GetString("do_ErrorReportingEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string do_ErrorReportingStatus {
            get {
                return ResourceManager.GetString("do_ErrorReportingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string do_ErrorReportingStatusDisabled {
            get {
                return ResourceManager.GetString("do_ErrorReportingStatusDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string do_ErrorReportingStatusEnabled {
            get {
                return ResourceManager.GetString("do_ErrorReportingStatusEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string do_Language {
            get {
                return ResourceManager.GetString("do_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set saved timer interval at startup.
        /// </summary>
        public static string do_MMTimerStartUpSet {
            get {
                return ResourceManager.GetString("do_MMTimerStartUpSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string do_Save {
            get {
                return ResourceManager.GetString("do_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        public static string do_Seconds {
            get {
                return ResourceManager.GetString("do_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show server information in tab header.
        /// </summary>
        public static string do_ShowServerInfoInTabs {
            get {
                return ResourceManager.GetString("do_ShowServerInfoInTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tab, only if server started.
        /// </summary>
        public static string do_ShowTabsOnlyIfServerStarted {
            get {
                return ResourceManager.GetString("do_ShowTabsOnlyIfServerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string do_Title {
            get {
                return ResourceManager.GetString("do_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server &quot;{0}&quot; will not be restarted because it crashed {1} times for {2} seconds..
        /// </summary>
        public static string log_CrashCountMaxLimit {
            get {
                return ResourceManager.GetString("log_CrashCountMaxLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Killing the process of server &quot;{0}&quot;..
        /// </summary>
        public static string log_KillProcessShutdown {
            get {
                return ResourceManager.GetString("log_KillProcessShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal shutdown for server &quot;{0}&quot; failed..
        /// </summary>
        public static string log_NormalShutdownFailed {
            get {
                return ResourceManager.GetString("log_NormalShutdownFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process is already killed..
        /// </summary>
        public static string log_ProcessAlreadyKilled {
            get {
                return ResourceManager.GetString("log_ProcessAlreadyKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server &quot;{0}&quot; is already started..
        /// </summary>
        public static string log_ServerAlreadyStarted {
            get {
                return ResourceManager.GetString("log_ServerAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server &quot;{0}&quot; is already stopped..
        /// </summary>
        public static string log_ServerAlreadyStopped {
            get {
                return ResourceManager.GetString("log_ServerAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server &quot;{0}&quot; crashed.\nConsole before crash:\n========================\n{1}\n========================\n.
        /// </summary>
        public static string log_ServerCrashed {
            get {
                return ResourceManager.GetString("log_ServerCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server &quot;{0}&quot; crashed on map {1}.\nConsole before crash:\n========================\n{2}\n========================\n.
        /// </summary>
        public static string log_ServerCrashedOnMap {
            get {
                return ResourceManager.GetString("log_ServerCrashedOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server &quot;{0}&quot; crashed.\nConsole before crash:\n========================\n{1}\n========================\nDialog box title: {2}\nDialog box message: {3}\n.
        /// </summary>
        public static string log_ServerCrashedWithDialog {
            get {
                return ResourceManager.GetString("log_ServerCrashedWithDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server &quot;{0}&quot; crashed on map {1}.\nConsole before crash:\n========================\n{2}\n========================\nDialog box title: {3}\nDialog box message: {4}\n.
        /// </summary>
        public static string log_ServerCrashedWithDialogOnMap {
            get {
                return ResourceManager.GetString("log_ServerCrashedWithDialogOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start failed. File &quot;{0}&quot; is not exists..
        /// </summary>
        public static string log_StartFailedFileIsNotExists {
            get {
                return ResourceManager.GetString("log_StartFailedFileIsNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting MM-timer from configuration value to {0}..
        /// </summary>
        public static string log_StartupTimerSet {
            get {
                return ResourceManager.GetString("log_StartupTimerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server &quot;{0}&quot; successful started..
        /// </summary>
        public static string log_SuccessfulStarted {
            get {
                return ResourceManager.GetString("log_SuccessfulStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server &quot;{0}&quot; successful stopped..
        /// </summary>
        public static string log_SuccessfulStopped {
            get {
                return ResourceManager.GetString("log_SuccessfulStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-timer current value: {0}..
        /// </summary>
        public static string log_TimerIntervalActual {
            get {
                return ResourceManager.GetString("log_TimerIntervalActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-timer min value: {0}..
        /// </summary>
        public static string log_TimerIntervalMax {
            get {
                return ResourceManager.GetString("log_TimerIntervalMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-timer max value: {0}..
        /// </summary>
        public static string log_TimerIntervalMin {
            get {
                return ResourceManager.GetString("log_TimerIntervalMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying normal shutdown for server &quot;{0}&quot;..
        /// </summary>
        public static string log_TryingNormalShutdown {
            get {
                return ResourceManager.GetString("log_TryingNormalShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to start server &quot;{0}&quot;..
        /// </summary>
        public static string log_TryingToStart {
            get {
                return ResourceManager.GetString("log_TryingToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create hook..
        /// </summary>
        public static string log_UnableToCreateHook {
            get {
                return ResourceManager.GetString("log_UnableToCreateHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set affinity..
        /// </summary>
        public static string log_UnableToSetAffinity {
            get {
                return ResourceManager.GetString("log_UnableToSetAffinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set priority..
        /// </summary>
        public static string log_UnableToSetPriority {
            get {
                return ResourceManager.GetString("log_UnableToSetPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to wait for Input Idle..
        /// </summary>
        public static string log_UnableToWaitForInputIdle {
            get {
                return ResourceManager.GetString("log_UnableToWaitForInputIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to access the registry.
        /// </summary>
        public static string mb_NotEnoughRights {
            get {
                return ResourceManager.GetString("mb_NotEnoughRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough rights.
        /// </summary>
        public static string mb_NotEnoughRightsTitle {
            get {
                return ResourceManager.GetString("mb_NotEnoughRightsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All players: {0}/{1}.
        /// </summary>
        public static string mw_AllPlayersCount {
            get {
                return ResourceManager.GetString("mw_AllPlayersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string mw_CancelOperation {
            get {
                return ResourceManager.GetString("mw_CancelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string mw_cm_Properties {
            get {
                return ResourceManager.GetString("mw_cm_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string mw_cm_RemoveServer {
            get {
                return ResourceManager.GetString("mw_cm_RemoveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string mw_cm_StartServer {
            get {
                return ResourceManager.GetString("mw_cm_StartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string mw_cm_StopServer {
            get {
                return ResourceManager.GetString("mw_cm_StopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string mw_dgsl_Active {
            get {
                return ResourceManager.GetString("mw_dgsl_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto restart.
        /// </summary>
        public static string mw_dgsl_AutoRestart {
            get {
                return ResourceManager.GetString("mw_dgsl_AutoRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command line arguments.
        /// </summary>
        public static string mw_dgsl_CmdArguments {
            get {
                return ResourceManager.GetString("mw_dgsl_CmdArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crashes.
        /// </summary>
        public static string mw_dgsl_Crashes {
            get {
                return ResourceManager.GetString("mw_dgsl_Crashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curent map.
        /// </summary>
        public static string mw_dgsl_CurrentMap {
            get {
                return ResourceManager.GetString("mw_dgsl_CurrentMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fps.
        /// </summary>
        public static string mw_dgsl_Fps {
            get {
                return ResourceManager.GetString("mw_dgsl_Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string mw_dgsl_Players {
            get {
                return ResourceManager.GetString("mw_dgsl_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name.
        /// </summary>
        public static string mw_dgsl_ServerName {
            get {
                return ResourceManager.GetString("mw_dgsl_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string mw_dgsl_Status {
            get {
                return ResourceManager.GetString("mw_dgsl_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string mw_gb_Actions {
            get {
                return ResourceManager.GetString("mw_gb_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer interval.
        /// </summary>
        public static string mw_gb_TimerInterval {
            get {
                return ResourceManager.GetString("mw_gb_TimerInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval between starts (in seconds):.
        /// </summary>
        public static string mw_lbl_IntervalBetweenStarts {
            get {
                return ResourceManager.GetString("mw_lbl_IntervalBetweenStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you realy want to exit?.
        /// </summary>
        public static string mw_mb_ExitConfirmation {
            get {
                return ResourceManager.GetString("mw_mb_ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string mw_mb_ExitConfirmationTitle {
            get {
                return ResourceManager.GetString("mw_mb_ExitConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to remove server &quot;{0}&quot;?.
        /// </summary>
        public static string mw_mb_RemoveConfirmation {
            get {
                return ResourceManager.GetString("mw_mb_RemoveConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server remove.
        /// </summary>
        public static string mw_mb_RemoveConfirmationTitle {
            get {
                return ResourceManager.GetString("mw_mb_RemoveConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Source.
        /// </summary>
        public static string mw_menu_AddGoldSourceServer {
            get {
                return ResourceManager.GetString("mw_menu_AddGoldSourceServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hltv.
        /// </summary>
        public static string mw_menu_AddHltvServer {
            get {
                return ResourceManager.GetString("mw_menu_AddHltvServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add server.
        /// </summary>
        public static string mw_menu_AddServer {
            get {
                return ResourceManager.GetString("mw_menu_AddServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string mw_menu_AddSourceServer {
            get {
                return ResourceManager.GetString("mw_menu_AddSourceServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string mw_menu_Edit {
            get {
                return ResourceManager.GetString("mw_menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string mw_menu_Exit {
            get {
                return ResourceManager.GetString("mw_menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string mw_menu_File {
            get {
                return ResourceManager.GetString("mw_menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import servers.
        /// </summary>
        public static string mw_menu_ImportServers {
            get {
                return ResourceManager.GetString("mw_menu_ImportServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string mw_menu_Options {
            get {
                return ResourceManager.GetString("mw_menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove server.
        /// </summary>
        public static string mw_menu_RemoveServer {
            get {
                return ResourceManager.GetString("mw_menu_RemoveServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server properties.
        /// </summary>
        public static string mw_menu_ServerProperties {
            get {
                return ResourceManager.GetString("mw_menu_ServerProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Hlds Launcher options.
        /// </summary>
        public static string mw_OldHldslOptionsFile {
            get {
                return ResourceManager.GetString("mw_OldHldslOptionsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string mw_SendConsoleCommand {
            get {
                return ResourceManager.GetString("mw_SendConsoleCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import server &quot;{0}&quot; successful..
        /// </summary>
        public static string mw_ServerImported {
            get {
                return ResourceManager.GetString("mw_ServerImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start all.
        /// </summary>
        public static string mw_StartAllServers {
            get {
                return ResourceManager.GetString("mw_StartAllServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start selected.
        /// </summary>
        public static string mw_StartSelectedServer {
            get {
                return ResourceManager.GetString("mw_StartSelectedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for servers start....
        /// </summary>
        public static string mw_StatusWaitingForServersStart {
            get {
                return ResourceManager.GetString("mw_StatusWaitingForServersStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop all.
        /// </summary>
        public static string mw_StopAllServers {
            get {
                return ResourceManager.GetString("mw_StopAllServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop selected.
        /// </summary>
        public static string mw_StopSelectedServer {
            get {
                return ResourceManager.GetString("mw_StopSelectedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main log.
        /// </summary>
        public static string mw_tcsl_MainLog {
            get {
                return ResourceManager.GetString("mw_tcsl_MainLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .net Hlds Launcher 2 - Double click to hide / show.
        /// </summary>
        public static string mw_ti_Text {
            get {
                return ResourceManager.GetString("mw_ti_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual:.
        /// </summary>
        public static string mw_TimerIntervalActual {
            get {
                return ResourceManager.GetString("mw_TimerIntervalActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max:.
        /// </summary>
        public static string mw_TimerIntervalMax {
            get {
                return ResourceManager.GetString("mw_TimerIntervalMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min:.
        /// </summary>
        public static string mw_TimerIntervalMin {
            get {
                return ResourceManager.GetString("mw_TimerIntervalMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string mw_TimerIntervalRefreshTimer {
            get {
                return ResourceManager.GetString("mw_TimerIntervalRefreshTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string mw_TimerIntervalSetTimer {
            get {
                return ResourceManager.GetString("mw_TimerIntervalSetTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for a new version....
        /// </summary>
        public static string mw_upd_CheckingNewVersion {
            get {
                return ResourceManager.GetString("mw_upd_CheckingNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update failed. Click to recheck....
        /// </summary>
        public static string mw_upd_FailCheckForUpdate {
            get {
                return ResourceManager.GetString("mw_upd_FailCheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ({0}) version is available. Click to download....
        /// </summary>
        public static string mw_upd_NewVersionAvailable {
            get {
                return ResourceManager.GetString("mw_upd_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available. Click to recheck....
        /// </summary>
        public static string mw_upd_NoNewVersionAvailable {
            get {
                return ResourceManager.GetString("mw_upd_NoNewVersionAvailable", resourceCulture);
            }
        }
    }
}
